### ISSUE TITLE
It is not working on console enviroment

### ISSUE THREAD

**Issue by gkucmierz** [subprotocol/genetic-js#1]
Probably eval is causing errors
![zrzut ekranu 2015-04-07 o 01 59 00](https://cloud.githubusercontent.com/assets/739084/7014793/b96cec7e-dcc9-11e4-973b-1b0411deb161.png)

**Comment by vrockai** [comment]
@subprotocol , was this issue closed because it lacks information?

**Comment by blonkm** [comment]
Maybe you just need to include the underscore library?
https://underscorejs.org/
