### ISSUE TITLE
complex solutions

### ISSUE THREAD

**Issue by gkucmierz** [subprotocol/genetic-js#2]
Correct me if I am wrong.
This library looks very nice, but its useless for more complex problems.
It is impossible to use in seed, fitness or any oter functions complex calculations that needs to call external functions from another library. References are not working, because code is stringified first to make possible passing it to webworker.
This library require to be rewrited I think.

**Comment by gkucmierz** [comment]
Ok, I found another promising library: https://github.com/dolphin278/genetic

**Comment by subprotocol** [comment]
yeah, that is the downside of web workers.  What you can do is separately load the library inside the webworker context and get access that way, but the objects that move around do need to be string-ified.
