### ISSUE TITLE
Where is genetic.evolve api documentation?

### ISSUE THREAD

**Issue by coreyferguson** [subprotocol/genetic-js#4]
I see [this](https://github.com/subprotocol/genetic-js/blob/master/examples/curve-fitter.html#L494) line of code in examples but no mention at what parameters it accepts and what name they are given within context of other genetic functions.

The `config` parameter is pretty obvious. What about the `userData` parameter? Is the second parameter supplied to genetic.evolve function always referenced with  `this.userData` from within api functions [example](https://github.com/subprotocol/genetic-js/blob/master/examples/curve-fitter.html#L124)? What is the intent of this variable? Is it meant to hold any arbitrary data I wish for later reference?

**Comment by bryanbecker** [comment]
a lot of the genetic functions don't have access to variable and functions outside their scope.  You have to add them into userData
